# Generated by Django 5.2.8 on 2025-11-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('CALIDOS', 'Calidos'), ('FRIOS', 'Frios'), ('GRISES', 'Grises'), ('PASTELES', 'Pasteles'), ('VIVOS', 'Vivos')], max_length=30)),
                ('popularidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pintura',
                'verbose_name_plural': 'Pinturas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sellador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sellador',
                'verbose_name_plural': 'Selladores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=30)),
                ('pais', models.CharField(choices=[('MEXICO', 'Mexico'), ('ESTADOS UNIDOS', 'Estados Unidos'), ('GUATEMALA', 'Guatemala'), ('EL SALVADOR', 'El Salvador'), ('HONDURAS', 'Honduras'), ('COSTA RICA', 'Costa Rica'), ('PANAMA', 'Panama')], max_length=30)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=50)),
                ('num_domicilio', models.CharField(max_length=10)),
                ('detalles', models.CharField(default='INFORMACION DEL DOMICILIO', max_length=250)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Personalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('pintura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizados', to='colormania.pintura')),
            ],
            options={
                'verbose_name': 'Personalizado',
                'verbose_name_plural': 'Personalizados',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('MERCADO PAGO', 'Mercado Pago'), ('OXXO', 'Oxxo')], max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('personalizados', models.ManyToManyField(related_name='pedidos', to='colormania.personalizado')),
                ('productos', models.ManyToManyField(related_name='pedidos', to='colormania.producto')),
                ('selladores', models.ManyToManyField(related_name='pedidos', to='colormania.sellador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='colormania.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
