# Generated by Django 5.2.8 on 2025-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colormania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintura',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='img_productos/'),
        ),
    ]
